//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroManagerClient.Resources.Languages; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroManagerClient.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Breached Credentials.
    /// </summary>
    public static string BreachedCredentials {
        get {
            return ResourceManager.GetString("BreachedCredentials", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Choose Language.
    /// </summary>
    public static string ChooseLanguage {
        get {
            return ResourceManager.GetString("ChooseLanguage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Choose Theme.
    /// </summary>
    public static string ChooseTheme {
        get {
            return ResourceManager.GetString("ChooseTheme", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Choose a type.
    /// </summary>
    public static string ChooseType {
        get {
            return ResourceManager.GetString("ChooseType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Close.
    /// </summary>
    public static string Close {
        get {
            return ResourceManager.GetString("Close", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Confirm New Password.
    /// </summary>
    public static string ConfirmNewPassword {
        get {
            return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Copy.
    /// </summary>
    public static string Copy {
        get {
            return ResourceManager.GetString("Copy", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Credential Report.
    /// </summary>
    public static string CredentialReport {
        get {
            return ResourceManager.GetString("CredentialReport", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Credential Types.
    /// </summary>
    public static string CredentialTypes {
        get {
            return ResourceManager.GetString("CredentialTypes", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Credit Card.
    /// </summary>
    public static string CreditCard {
        get {
            return ResourceManager.GetString("CreditCard", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Dashboard.
    /// </summary>
    public static string Dashboard {
        get {
            return ResourceManager.GetString("Dashboard", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Date Added.
    /// </summary>
    public static string DateAdded {
        get {
            return ResourceManager.GetString("DateAdded", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Edit.
    /// </summary>
    public static string Edit {
        get {
            return ResourceManager.GetString("Edit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Export.
    /// </summary>
    public static string Export {
        get {
            return ResourceManager.GetString("Export", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Field.
    /// </summary>
    public static string Field {
        get {
            return ResourceManager.GetString("Field", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filter.
    /// </summary>
    public static string Filter {
        get {
            return ResourceManager.GetString("Filter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Button that opens a filter dialog.
    /// </summary>
    public static string FilterButtonDescription {
        get {
            return ResourceManager.GetString("FilterButtonDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hide Values.
    /// </summary>
    public static string HideValues {
        get {
            return ResourceManager.GetString("HideValues", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Identity.
    /// </summary>
    public static string Identity {
        get {
            return ResourceManager.GetString("Identity", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Index.
    /// </summary>
    public static string Index {
        get {
            return ResourceManager.GetString("Index", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Information.
    /// </summary>
    public static string Information {
        get {
            return ResourceManager.GetString("Information", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Languages.
    /// </summary>
    public static string Languages {
        get {
            return ResourceManager.GetString("Languages", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Last Modified.
    /// </summary>
    public static string LastModified {
        get {
            return ResourceManager.GetString("LastModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Login.
    /// </summary>
    public static string Login {
        get {
            return ResourceManager.GetString("Login", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Logins.
    /// </summary>
    public static string Logins {
        get {
            return ResourceManager.GetString("Logins", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Master Password.
    /// </summary>
    public static string MasterPassword {
        get {
            return ResourceManager.GetString("MasterPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter Master Password Again.
    /// </summary>
    public static string MasterPasswordAgain {
        get {
            return ResourceManager.GetString("MasterPasswordAgain", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to You must be logged in.
    /// </summary>
    public static string MustBeLoggedIn {
        get {
            return ResourceManager.GetString("MustBeLoggedIn", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to You must enter a password.
    /// </summary>
    public static string MustEnterPassword {
        get {
            return ResourceManager.GetString("MustEnterPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to You must enter your password again.
    /// </summary>
    public static string MustReEnterPassword {
        get {
            return ResourceManager.GetString("MustReEnterPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to My Credentials.
    /// </summary>
    public static string MyCredentials {
        get {
            return ResourceManager.GetString("MyCredentials", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to New Password.
    /// </summary>
    public static string NewPassword {
        get {
            return ResourceManager.GetString("NewPassword", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No title provided.
    /// </summary>
    public static string NoTitle {
        get {
            return ResourceManager.GetString("NoTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ok.
    /// </summary>
    public static string Ok {
        get {
            return ResourceManager.GetString("Ok", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Your passwords don&apos;t match.
    /// </summary>
    public static string PasswordDontMatch {
        get {
            return ResourceManager.GetString("PasswordDontMatch", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Your password is incorrect.
    /// </summary>
    public static string PasswordIncorrect {
        get {
            return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Passwords.
    /// </summary>
    public static string Passwords {
        get {
            return ResourceManager.GetString("Passwords", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Recently Updated.
    /// </summary>
    public static string RecentlyUpdated {
        get {
            return ResourceManager.GetString("RecentlyUpdated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Recovery Keys.
    /// </summary>
    public static string RecoveryKeys {
        get {
            return ResourceManager.GetString("RecoveryKeys", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save.
    /// </summary>
    public static string Save {
        get {
            return ResourceManager.GetString("Save", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sa.
    /// </summary>
    public static string SaveFilter {
        get {
            return ResourceManager.GetString("SaveFilter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search for login, identity, etc....
    /// </summary>
    public static string SearchHomePage {
        get {
            return ResourceManager.GetString("SearchHomePage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Secure Note.
    /// </summary>
    public static string SecureNote {
        get {
            return ResourceManager.GetString("SecureNote", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public static string Settings {
        get {
            return ResourceManager.GetString("Settings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Show Data.
    /// </summary>
    public static string ShowData {
        get {
            return ResourceManager.GetString("ShowData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Show Values.
    /// </summary>
    public static string ShowValues {
        get {
            return ResourceManager.GetString("ShowValues", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Themes.
    /// </summary>
    public static string Themes {
        get {
            return ResourceManager.GetString("Themes", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Title.
    /// </summary>
    public static string Title {
        get {
            return ResourceManager.GetString("Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Today.
    /// </summary>
    public static string Today {
        get {
            return ResourceManager.GetString("Today", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Total of 2FA passwords.
    /// </summary>
    public static string Total2FAPasswords {
        get {
            return ResourceManager.GetString("Total2FAPasswords", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Total of reused passwords.
    /// </summary>
    public static string TotalReusedPasswords {
        get {
            return ResourceManager.GetString("TotalReusedPasswords", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Total of weak passwords.
    /// </summary>
    public static string TotalWeakPasswords {
        get {
            return ResourceManager.GetString("TotalWeakPasswords", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Type.
    /// </summary>
    public static string Type {
        get {
            return ResourceManager.GetString("Type", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Value.
    /// </summary>
    public static string Value {
        get {
            return ResourceManager.GetString("Value", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Verify Password.
    /// </summary>
    public static string VerifyPassword {
        get {
            return ResourceManager.GetString("VerifyPassword", resourceCulture);
        }
    }
}
