global using AstroManagerClient.Library.Api.Interfaces;
global using AstroManagerClient.Library.Models.Interfaces;
global using Microsoft.Extensions.Configuration;
global using System.Net.Http.Headers;
global using AstroManagerClient.Library.Models;
global using AstroManagerClient.Library.Storage.Interfaces;
global using System.Net.Http.Json;
global using System.Security.Cryptography;
global using System.Text.Json;